# Generated by Django 5.0.6 on 2025-08-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0028_partinstrumentsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWING', 'Reviewing'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=20),
        ),
    ]
